version: 2
jobs:
  build:
    environment:
      - GOPATH: /home/circleci/go
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/kasumits/hatenadiary.jp
    steps:
      # ここから https://blog.a-know.me/entry/2018/03/04/215345 の記述をそのまま拝借します
      # GOPATH の設定。environment だけじゃ無理っぽい？ https://qiita.com/tomiyan/items/6142113011243c5b5cd1
      - run: echo 'export PATH=${PATH}:${GOPATH}/bin' >> $BASH_ENV
      # blogsync 用の config ファイルを置く場所の作成
      - run: mkdir -p ~/.config/blogsync
      # blogsync 用の config ファイルの書き出し。コロンをエスケープするために使ったダブルクォートを tr コマンドで無理矢理削除している
      - run: echo -e "${HATEBLO_URL}\":\"\n  username\":\" ${HATEBLO_USERNAME}\n  password\":\" ${HATEBLO_PASSWORD}\n  local_root\":\" /go/src/github.com/kasumits/hatenadiary.jp\n  omit_domain\":\" true" | tr -d \" >> ~/.config/blogsync/config.yaml
      # ここまで

#      - run: go get gopkg.in/yaml.v2
#      - run: go get github.com/motemen/go-colorine
#      - run: go get github.com/motemen/go-loghttp
#      - run: go get github.com/motemen/go-wsse
#      - run: go get github.com/cpuguy83/go-md2man
#      - run: GO111MODULE=on go get github.com/urfave/cli/v2

      # - run: git clone https://github.com/motemen/blogsync.git ${GOPATH}/src/github.com/motemen/blogsync
      # - run: git clone https://github.com/motemen/go-loghttp.git ${GOPATH}/src/github.com/motemen/go-loghttp
      # - run: git clone https://github.com/motemen/go-wsse.git ${GOPATH}/src/github.com/motemen/go-wsse
      
      # - run: git clone https://github.com/cpuguy83/go-md2man/v2/md2man.git ${GOPATH}/src/github.com/cpuguy83/go-md2man/v2/md2man
      # - run: git clone https://github.comdaviddengcn/go-colortext.git ${GOPATH}/src/github.com/daviddengcn/go-colortext
      # - run: git clone https://github.com/motemen/go-nuts/roundtime.git ${GOPATH}/src/github.com/motemen/go-nuts/roundtime
      # - run: cd ${GOPATH}/src/github.com/motemen/blogsync && go build -o blogsync

      - run: GO111MODULE=on go get github.com/motemen/blogsync
      # リポジトリからチェックアウト
      - checkout

      - run:
          name: pull blog entries
          command: |
            blogsync pull ${HATEBLO_URL}

      - run:
          name: git diff
          command: |
            git diff origin/master...${CIRCLE_BRANCH}
